### ISSUE TITLE
Better error handling

### ISSUE THREAD

**Issue by sleptor** [himiklab/yii2-recaptcha-widget#102]
Currently, you throw an exception here
https://github.com/himiklab/yii2-recaptcha-widget/blob/master/src/ReCaptchaValidator2.php#L82

That's why sometimes my users see 500 error. 
I guess it would be better to set isValid = false instead of Exception. It will make the user experience better.

At least, you may add an option to change this behavior like 'throwException' => false.

**Comment by igor-netFantom** [comment]
Agree. I have got exception 'Invalid recaptcha verify response.' on response: 
Array
(
    [success] => 
    [error-codes] => Array
        (
            [0] => timeout-or-duplicate
        )
)
Should be option to get validation error instead of exception.

**Comment by petrovich24** [comment]
I do follow to solve this problem:
1. add custom validation rule like this ['verifyCode', 'verifyRecaptcha']
2. add function to model
    public function verifyRecaptcha($attribute, $params)
    {
        $v = \Yii::createObject(\himiklab\yii2\recaptcha\ReCaptchaValidator2::class);
        try {
            $v->validate($this->{$attribute});
        } catch (\Exception $e) {
            $this->addError($attribute,'Invalid captcha');
        }
    }
