### ISSUE TITLE
Yii 2.0.39 upgrade problem

### ISSUE THREAD

**Issue by mauriziocingolani** [himiklab/yii2-recaptcha-widget#113]
Hello, I don't know if you're still mantaining this, but you code broke when I updated my applications ti Yii 2.0.39.
The problem seems to be in the ReCaptchaValidator2 class. If I properly include the missing class (Yii\httpclient\Request) with a "use" statement the error goes away, but I get another one when I submit the form.

I hope you can take a look at this.

Thank you

![Schermata 2020-11-12 alle 09 47 15](https://user-images.githubusercontent.com/4015015/98916955-12118b00-24cc-11eb-85a4-a80de32fac82.png)

![Schermata 2020-11-12 alle 09 41 58](https://user-images.githubusercontent.com/4015015/98916513-8bf54480-24cb-11eb-9a29-8c50d7f4c5af.png)

**Comment by kshtayat** [comment]
When this will be released?
