### ISSUE TITLE
google recaptcha on popup issue

### ISSUE THREAD

**Issue by ffuurrqqaann** [himiklab/yii2-recaptcha-widget#12]
Hi,

I am using this extension in yii2 and I have a signup page on popup. At first if we click on the popup recaptcha appears but when we click on the button to show the popup second time the google recaptcha didn't show up. Can anybody help me with this issue??

Thanks and Regards,
Furqan Ahmed.

**Comment by sashsvamir** [comment]
To loading single ajax page with reCaptcha **twice** (and more times), you need reset grecaptcha and render it again when signup page with captcha has been loaded. Also to perform this action, you need loading script `app.js` with params `explicit` and `onload` like this: `//www.google.com/recaptcha/api.js?hl=ru&render=explicit&onload=CaptchaCallback`
i'm resolve this issue with following:
```js
if (typeof verifyCode !== 'undefined') {
	grecaptcha.reset(verifyCode);
	CaptchaCallback();
}
var CaptchaCallback = function() {
	verifyCode = grecaptcha.render($('.g-recaptcha')[0], {
	  'sitekey' : 'your public key here'
	});
};
```
Now i'm not have idea how to perform this with this widget without rewriting class `ReCaptcha.php`, but If @himiklab author of this widget write here advice it wil be nice

**Comment by kehindesalaam** [comment]
please has a fix been found for this

**Comment by himiklab** [comment]
With pleasure I will accept a pool request.

**Comment by lgXenos** [comment]
@sashsvamir say please, what we need reset? all of old inputs? or only 1 new?
My current code render pajaxed recaptcha. But when ActiveForm are submiteing - I'm get JS-errors :(

![image](https://user-images.githubusercontent.com/14957311/34395591-859136d4-eb72-11e7-89dd-44a8f1009d56.png)
![image](https://user-images.githubusercontent.com/14957311/34395600-a6d35250-eb72-11e7-91da-cc9af265b3a5.png)

And it is very unfortunate that the himiklab does not want find working solution and only waiting for us
 :(

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/bc9df57a2b420aa7deaec4f6556ff79d57fa435b
