### ISSUE TITLE
Only show captcha after 2nd or 3rd failed login attempt

### ISSUE THREAD

**Issue by nsanden** [himiklab/yii2-recaptcha-widget#21]
That would be a neat feature. Guess i'll try and figure out some way to accomplish it outside the extension but never the less wanted to bring it up here.

**Comment by farzan-ghalami** [comment]
you have to create an scenario for recapcha.
in the controller check this 
if (Yii::app()->user->getState('attempts-login') > 3) { 
                    $model->scenario = 'withCaptcha'; //useful only for view
                }
then 
in  the view check this
if ($model->scenario == 'withCaptcha' ) 
echo <div class"recapcha"></div>
