### ISSUE TITLE
PHP7 issue: component initialization

### ISSUE THREAD

**Issue by tibee** [himiklab/yii2-recaptcha-widget#22]
In PHP 7, `empty()` behaves different than PHP 5. See following code. In PHP 7, evaluating `!empty(Yii::$app->reCaptcha->siteKey)` does NOT initialize the `reCaptcha` component, although PHP 5 does. So every time Exception is thrown.

```php
        if (empty($this->siteKey)) {
            if (!empty(Yii::$app->reCaptcha->siteKey)) {
                $this->siteKey = Yii::$app->reCaptcha->siteKey;
            } else {
                throw new InvalidConfigException('Required `siteKey` param isn\'t set.');
            }
        }
```

**Comment by himiklab** [comment]
On PHP 7.0.7 is all right.

**Comment by vasiluy-kondr** [comment]
I have the issue even on php 7.0.7 [here, have a look](https://github.com/yiisoft/yii2/issues/11771).

**Comment by Borales** [comment]
I can confirm this bug.
php 7.0.7. yii2 - from master

**Comment by xicond** [comment]
PHP 7.0.8-0ubuntu0.16.04.2 (cli) ( NTS )

this would return true even there's a value
`empty(Yii::$app->reCaptcha->siteKey)`

should workaround to assign to new variable
`$siteKey = Yii::$app->reCaptcha->siteKey;`
then 
`empty(Yii::$app->reCaptcha->siteKey)`
would be false

**Comment by zhukovra** [comment]
Can confirm bug in PHP 7.0.10

**Comment by nagyt234** [comment]
Please accept #28 and create a new release to solve this problem.
Thx

**Comment by himiklab** [comment]
Finally https://github.com/himiklab/yii2-recaptcha-widget/pull/38
