### ISSUE TITLE
Unable connection to the captcha server.

### ISSUE THREAD

**Issue by bxn5** [himiklab/yii2-recaptcha-widget#29]
I understand what it means, but anybody know why it's happening?

**Comment by koteq** [comment]
This exception [should contain error message](https://github.com/himiklab/yii2-recaptcha-widget/blob/0e13a167b408f979b2c5ea5ceb444d169902570c/ReCaptchaValidator.php#L138) from curl but unfortunately it may be empty for some reason. Maybe it's a good idea to add errno to the exception message too.
