### ISSUE TITLE
Setting unknown property

### ISSUE THREAD

**Issue by AlexMerser21** [himiklab/yii2-recaptcha-widget#3]
After submit form:
http://prntscr.com/62jvlp
http://prntscr.com/62jvtm

**Comment by himiklab** [comment]
Здравствуйте!
Покажите код связанный с модулем.

**Comment by AlexMerser21** [comment]
Насчет этой проблемы разобрался. Забыл вставить `public $reCaptcha;`
Будет каптча работать на локальном сервере(домен localhost/)?
