### ISSUE TITLE
Постоянно ловлю ошибку в чем проблема непойму

### ISSUE THREAD

**Issue by i-coder** [himiklab/yii2-recaptcha-widget#32]
array(1) { ["reCaptcha"]=> array(1) { [0]=> string(55) "Неправильный проверочный код." } }

**Comment by WadeShuler** [comment]
Can you please provide more information?

What is your entry in the Yii2 config for this extension? How are you loading it in your view? Did you enter in a siteKey and secret in your config? Is this issue local, or on a server? What version of PHP?

**Comment by DarthLegiON** [comment]
I have the same issue.
rule:
```php
[['reCaptcha'], ReCaptchaValidator::className(), 'message' => 'Подтвердите, что вы не робот'],
```
config:
```php
'reCaptcha' => [
            'class' => 'himiklab\yii2\recaptcha\ReCaptcha',
            'name' => 'reCaptcha',
            'siteKey' => '...',
            'secret' => '...',
        ],
```
view:
```php
<?=  $form->field($model, 'reCaptcha')->widget(ReCaptcha::className(), [
        'name' => 'NewUserRegisterForm[reCaptcha]',
    ])->label(false) ?>
```

PHP 7.0.12, CentOS 6 server

**Comment by DarthLegiON** [comment]
Google reCAPTCHA service in your Curl returns success. Here is var_dump($response):
```
array(3) { ["success"]=> bool(false) ["challenge_ts"]=> string(20) "2016-12-23T16:49:06Z" ["hostname"]=> string(19) "hostname.ru" }
```
But Validator is still returns error. Why?

**Comment by DarthLegiON** [comment]
I know, it happens because of ajax validation. This validator must be shut down on ajax validation via scenario and it must be called only once as final validator.

**Comment by evaldemar** [comment]
for ajax validation use
`
                'reCaptcha', ReCaptchaValidator::className(), 'message' => 'Подтвердите, что Вы не робот',
                'when' => function($model){
                    return !$model->getErrors() && !Yii::$app->request->isAjax /* !Yii::$app->request->post('ajax')*/;
                },
            ],
`
