### ISSUE TITLE
sitekey and secret key should not be required in dev mode

### ISSUE THREAD

**Issue by WadeShuler** [himiklab/yii2-recaptcha-widget#33]
When running from localhost, Google does not require the sitekey and secret. It will still work so you can test locally. Your extension throws an error when these are left blank and forces me to put something in them, which breaks local testing.

This should check if Yii is running in dev mode before requiring that we enter them in, so we can test and not see a sitekey error.

**Comment by WadeShuler** [comment]
According to the docs, we are not able to use an empty siteKey or secret. [https://developers.google.com/recaptcha/docs/faq](https://developers.google.com/recaptcha/docs/faq)

It says we should use specific values for localhost testing.

> Site key: 6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI
> Secret key: 6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe

I have modified this extension to automatically insert the siteKey and secret, when Yii is running in debug mode (ie: YII_DEBUG = true), which is usually locally. If anyone has a better way to handle it, let me know. I felt that checking the debug constant was sufficient.

All you have to do is leave the values empty in your config:

    'reCaptcha' => [
            'name' => 'reCaptcha',
            'class' => 'himiklab\yii2\recaptcha\ReCaptcha',
            'siteKey' => '',
            'secret'  => '',
        ],

**Comment by Kompaneytsev** [comment]
another solution, you can add localhost url to domains in your recaptcha options. for me it works.

**Comment by WadeShuler** [comment]
@Kompaneytsev That isn't a viable solution for fixing the problem the way it should be fixed. Google has provided a `siteKey` and `secret` for us to test with, without having to even setup Google reCaptcha. This extension should offer what Google provides out of the box. Remembering the built-in keys that Google provides, requires we go out and hunt for it. Requiring that we go modify our existing key(s) to allow localhost, requires we go login to our account and copy them for each project. So this extension should allow us to keep them empty, and will replace them with the Google provided defaults for us when in dev mode.

When working locally, or you push to a test server, we shouldn't have to go setup special keys for these. I can work 100% locally, push to test server, and when ready to move to clients server I can request that my client goes and gets me his keys. I don't have to worry about it until the very last step.

**Comment by himiklab** [comment]
Why not use ```YII_ENV_DEV ? '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'``` ...
