### ISSUE TITLE
multiple captcha for one page

### ISSUE THREAD

**Issue by xr0m3oz** [himiklab/yii2-recaptcha-widget#45]
https://www.google.com/recaptcha/api.js?onload=onloadCallback&render=explicit"
```
var onloadCallback = function() {

	var siteKey = 'key';
	$('.captcha').each(function(index) {

		grecaptcha.render($(this).attr('id'), {
			'sitekey' : siteKey
		});
	});
};
```
need ad to plagin for multiple captcha for one page

**Comment by oopkz** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/pull/20/files?short_path=04c6e90

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/pull/20/
