### ISSUE TITLE
validation failed if model is multiple multiple times

### ISSUE THREAD

**Issue by Bhoft** [himiklab/yii2-recaptcha-widget#48]
Hi i have just tested your widget and everything works as expected in the test mode with test mode sitekey.

With the normal siteKeys (so in real usage conditions) i have the problem that the model is validated multiple times.
$model->validate() is called multiple times because it is a multi model form and in several external traits from other extensions.

Therefore validate is called directly in the controller and then again in the save() function.

example call in my controller:
> if ($model->load(Yii::$app->request->post()) && $model->validate() && $model->save()) {

And because of this multiple validate call the validation fails.

Couldn't there be some sort of timeout added or some setting that that the validation was already successful? 

So it validation for the reCaptcha attribute isn't done again a second time?

Edit: 
I have solved this issue by validating by a behavior where i can check if the validation was already done or not for the current request.

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/c900ad07f801d3b8d850d3259aa2cc51be6d9132
