### ISSUE TITLE
Fatal Error with message 'Class 'himiklab\yii2\recaptcha\ReCaptchaValidator' not found' 

### ISSUE THREAD

**Issue by nasreekar** [himiklab/yii2-recaptcha-widget#53]
I tried to follow the steps mentioned in the ReadMe Description to add recaptcha widget. 
I have done everything but it is throwing the error as the *Title*

I tried adding the widget rule in composer.json file and did a `composer update` on terminal and I see this as below.
<img width="542" alt="screen shot 2017-10-10 at 4 36 58 pm" src="https://user-images.githubusercontent.com/13792317/31377007-49ee0f02-add9-11e7-863b-1df0b6627ce4.png">

My code:
*Signup form.php*
`public function rules()
    {
        return [
            ...
            [['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator::SignupForm(), 'secret' => 'secretkey', 'uncheckedMessage' => 'Please confirm that you are not a bot.']
        ];
    }`

*signup.php (view)*
`  <?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::SignupForm(),['siteKey' => 'sitekey']) ?>`

*main.php*
`return [
'components' => [
            'reCaptcha' => [
                'name' => 'reCaptcha',
                'class' => 'himiklab\yii2\recaptcha\ReCaptcha',
                'siteKey' => 'siteKey',
                'secret' => 'secret',
            ], 
... 
]`        

Did anyone face the same issue? Can someone help me in solving this. TIA

**Comment by Astrixen** [comment]
I copyed folder 'yii2-recaptcha-widget' to the same folder and renamed copy to 'yii2'
