### ISSUE TITLE
After cancel the modal the next modal doesnt show the recaptcha anymore

### ISSUE THREAD

**Issue by MarcoDuizer** [himiklab/yii2-recaptcha-widget#55]
Hello,

I implemented the recaptcha as in the example, and it works great. Only if I cancel the modal and then open another item from the list to create the modal the widget doesn't show anymore.
Is there a way to reset the recaptcha when i cancel the modal?
Thanks for your help!!

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/issues/12
