### ISSUE TITLE
yii not add class "has-error" to form-element

### ISSUE THREAD

**Issue by lgXenos** [himiklab/yii2-recaptcha-widget#57]
@himiklab 
Why in my form not present error-class from yii, when I'm click "Submit" on ActiveForm ?

As you can see - another required field have class with error
.
![](https://b.radikal.ru/b26/1712/2d/be841a5f6171.png)

**Comment by lgXenos** [comment]
С той скоростью, что ты реагируешь, не удивительно, что пулреквесты у тебя протухают, а ребятам их не хочется делать. Куда проще у себя поправить, т.к. приходится самому все раскапывать

**Comment by himiklab** [comment]
Я тут кому-то что-то должен?

**Comment by himiklab** [comment]
It is possible more in detail?
