### ISSUE TITLE
AJAX Validation

### ISSUE THREAD

**Issue by Borales** [himiklab/yii2-recaptcha-widget#6]
Статус капчи проверяется только 1 раз, последующие проверки - возвращают `false`.
Таким образом, невозможно сделать AJAX валидацию формы с полем капчи.

Возможно стоит расширить валидатор для сохранения только первой проверки капчи (кешировать на пару минут), а последующие - возвращать сохраненное состояние?

**Comment by himiklab** [comment]
Зачем AJAX валидация, когда виджет рекапчи сам отображает правильность ввода?

**Comment by ashatrov** [comment]
Внутри каптчи из фреймворка есть такое: "CAPTCHA validation should not be used in AJAX validation mode because it may fail the validation".
Может быть лучше исключать поле с каптчей из ajax валидации вот так:
"You may also turn AJAX validation on or off for individual input fields by configuring their yii\widgets\ActiveField::$enableAjaxValidation property."

Если кешировать, то во-первых, происходит привязка к наличию кеширования в проекте, а во-вторых , получается "глючное" поведение виджета, т.е. юзеры будут жаловаться "ПОМОГИТЕ! Я заполняю форму, а на не всегда работает. Я ввёл код а оно пишет, что код плохой! Как мне зарегистрироваться?"

А если это добавлять как доп.фичу, то по умолчанию выключать, а не включать кеш.

**Comment by Borales** [comment]
@anders-akero было бы так просто )
Валидация каптчи все-равно происходит, даже с отключенным `$enableAjaxValidation` (и срабатывает только первый раз). В самой модели срабатывает правило валидации атрибута каптчи - выдается результат валидации. 

По поводу кеша - даже в простом шаблоне проекта включено файловое кеширование (https://github.com/yiisoft/yii2/blob/master/apps/basic/config/web.php#L14).
Но добавить индикатор включения кеша в валидаторе - не проблема, добавлю.

**Comment by Borales** [comment]
@ashatrov было бы так просто )
Валидация каптчи все-равно происходит, даже с отключенным $enableAjaxValidation (и срабатывает только первый раз). В самой модели срабатывает правило валидации атрибута каптчи - выдается результат валидации.

По поводу кеша - даже в простом шаблоне проекта включено файловое кеширование (https://github.com/yiisoft/yii2/blob/master/apps/basic/config/web.php#L14).
Но добавить индикатор включения кеша в валидаторе - не проблема, добавлю.

**Comment by Borales** [comment]
@anders-akero sorry, typo in nickname

**Comment by Borales** [comment]
@ashatrov в PR добавил индикатор кеша в валидатор (по умолчанию - отключен).

**Comment by ashatrov** [comment]
Так это похоже баг фреймворка. Если я говорю !не проверять поле!, а оно проверяет, хотя рядом с полем сообщение не рисует, но проверяет.
По идее эта опция должна отключать валидацию, а не вывод сообщений об ошибках.

**Comment by Borales** [comment]
@himiklab какое будет решение по этой проблеме?

**Comment by tecnologiaterabyte** [comment]
Hi, ajaxvalidation disable to work in the captcha you must use:

        <?php $form = ActiveForm::begin([
            'id' => 'login-form-admin',
            'enableAjaxValidation' => true,
            'enableClientValidation' => false,
            'validateOnSubmit' => false, 
        ]) ?>

        <?= $form->field($model, 'reCaptcha', ['enableAjaxValidation' => false])->widget(
            \himiklab\yii2\recaptcha\ReCaptcha::className(), [
                'name' => 'reCaptcha',
                'siteKey' => \yii::$app->params['sitekeyrecaptcha'],
                'widgetOptions' => ['class' => 'recaptcha-login']
            ]
            )->label('reCaptcha') ?>

        <?php ActiveForm::end(); ?>

Work Fine.

https://github.com/yiisoft/yii2/issues/1456

**Comment by himiklab** [comment]
`enableAjaxValidation` = false точно не работает?

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/issues/6#issuecomment-78044771

**Comment by azadbey** [comment]
asas

**Comment by azadbey** [comment]
Thanks, good solution. And setting for captcha 'enableAjaxValidation' => false, really help only when setting 'validateOnSubmit' => false, default true

**Comment by progr000** [comment]
Вот такое решение проблемы придумал. Может кому то пригодится
`
    public function rules()
    {
        $rules = [
            [['user_name', 'user_email', 'password', 'password_repeat', 'acceptRules'], 'required'],
        ];

        if (!Yii::$app->request->isAjax) {
                $rules[] = [['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator::className(), 'secret' => Yii::$app->params['reCaptchaSecretKey']];
        }

        return $rules;
    }
`

**Comment by bemulima** [comment]
Если использовать pjax для формы то после обновления блока рекапча уже не запускается. Пробовал добавить:
```
<?php
    $this->registerJs(
        '$("document").ready(function(){
            
            $("#p_contact_form").on("pjax:end", function() {
            grecaptcha.render( $(\'.g-recaptcha\')[0], { sitekey : \'м\' });
            
            grecaptcha.reset()
        });
    });'
    );
?>
```
Теперь после submit блок обновляется и рекапча запускается но вот только значение в инпуту не передается т.е. вот этот jquery код не работает:

`var recaptchaCallback = function(response){jQuery('#{$inputId}').val(response);};`

как сделать так, чтоб после обновления блока с помощью pjax рекапча работал?

**Comment by amaduha** [comment]
Как использовать плагин, что бы использовать его одновременно в двух и более формах от разных моделей, на одной странице ? пробовал разные ИД прописывать, не катит. Отображается и работает только первая капча. Остальные не работают.
