### ISSUE TITLE
Problem with multiple captcha on one page

### ISSUE THREAD

**Issue by diozdeath19** [himiklab/yii2-recaptcha-widget#61]
Hi, I have 3 forms on one page. After reading this [topic](https://github.com/himiklab/yii2-recaptcha-widget/issues/45) i set different id's on my forms in widget options, but in result form don't returns error message when i simulate situation when i don't press on recaptcha button. Any ideas?

**Comment by himiklab** [comment]
Hello!
No. please show your code.

**Comment by diozdeath19** [comment]
config/web.php
`        'reCaptcha' => [
            'name' => 'reCaptcha',
            'class' => 'himiklab\yii2\recaptcha\ReCaptcha',
            'siteKey' => 'xxxxxxx',
            'secret' => 'xxxxxxxx',
        ],
`
in view
`                        <div class="col-md-12">
                            <?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className(), ['widgetOptions' => ['id' => 'recaptcha-form-1']])->label(false) ?>
                        </div>
`

in model
`    public function rules()
    {
        return [
            [['reCaptcha'], \himiklab\yii2\recaptcha\ReCaptchaValidator::className(), 'uncheckedMessage' => 'Подтвердите, что вы не робот', 'message' => 'Некорректный код']
        ];
    }
`

If i set id widgetOptions i don't receive error message even if i've one form with captcha on page but if i have one form without setting id in widget options, i've error

**Comment by himiklab** [comment]
Do not use `'widgetOptions' => ['id' =>...]` with ActiveForm, this breaks down yii validation. Several forms on the page should work without it.

**Comment by diozdeath19** [comment]
If I not use `'widgetOptions' => ['id' =>...]` , recaptcha renders on only one form

**Comment by himiklab** [comment]
Can you show the view code?

**Comment by diozdeath19** [comment]
First form on page
`                    <?php $form = ActiveForm::begin([
                        'options' => ['method' => 'post', 'onsubmit' => "yaCounter22074592.reachGoal('obrSubmit'); yaCounter22074592.reachGoal('top_order_examples');  return true;"],
                        'action' => ['site/contact'],
                    ]) ?>

                        <?= $form->field($mail, 'type')->hiddenInput(['value'=> 0 , 'style' => 'display:none'])->label(false); ?>

                        <div class="col-md-12">
                            <?= $form->field($mail, 'fio')->textInput(['placeholder' => "ИМЯ"])->label(false); ?>
                        </div>
                        <div class="col-md-12">
                            <?= $form->field($mail, 'email')->textInput(['placeholder' => "E-mail", 'class' => 'mail-email'])->label(false); ?>
                        </div>
                        <div class="col-md-12">
                            <?= $form->field($mail, 'phone')->textInput(['placeholder' => "Телефон", 'class' => 'mail-phone'])->label(false); ?>
                        </div>
                        <div class="col-md-12">
                            <?= $form->field($mail, 'comment')->textarea(['placeholder' => 'Комментарий', 'rows' => 6])->label(false); ?>
                        </div>

                        <div class="col-md-12">
                            <?= $form->field($mail, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className())->label(false) ?>
                        </div>

                        <div class="col-md-12">
                            <?= $form->field($mail, 'address')->hiddenInput(['value'=> '' , 'style' => 'display:none'])->label(false); ?>
                        </div>


                        
                        <div class="col-md-6">
                            <?= Html::submitButton('Заказать образцы') ?>
                        </div>

                    <?php ActiveForm::end(); ?>`
Second form on a page
`                    <?php $form = ActiveForm::begin([
                        'options' => ['method' => 'post', 'onsubmit' => "yaCounter22074592.reachGoal('brandSubmit'); return true;"],
                        'action' => ['site/contact'],
                    ]) ?>
                        <?= $form->field($mail, 'type')->hiddenInput(['value'=> 1 , 'style' => 'display:none'])->label(false); ?>

                        <div class="col-md-12">
                            <?= $form->field($mail, 'fio')->textInput(['placeholder' => "ИМЯ"])->label(false); ?>
                        </div>
                        <div class="col-md-12">
                            <?= $form->field($mail, 'email')->textInput(['placeholder' => "E-mail", 'class' => 'mail-email'])->label(false); ?>
                        </div>
                        <div class="col-md-12">
                            <?= $form->field($mail, 'phone')->textInput(['placeholder' => "Телефон", 'class' => 'mail-phone'])->label(false); ?>
                        </div>
                        <div class="col-md-12">
                            <?= $form->field($mail, 'comment')->textarea(['placeholder' => 'Комментарий', 'rows' => 6])->label(false); ?>
                        </div>

                        <div class="col-md-12">
                            <?= $form->field($mail, 'address')->hiddenInput(['value'=> '' , 'style' => 'display:none'])->label(false); ?>
                        </div>

                        <div class="col-md-12">
                            <?= $form->field($mail, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className())->label(false) ?>
                        </div>
                        
                        <div class="col-md-6">
                            <?= Html::submitButton('Заказать брендирование') ?>
                        </div>

                    <?php ActiveForm::end(); ?>`

**Comment by diozdeath19** [comment]
First form:
![_007](https://user-images.githubusercontent.com/25438889/36019996-1416169a-0d92-11e8-91a2-4493c0b02fba.png)
Second form:
![_008](https://user-images.githubusercontent.com/25438889/36020016-2ea64d54-0d92-11e8-901d-fed81190fcc8.png)

Recaptcha renders only on second form, because she is last on page

**Comment by himiklab** [comment]
Всё верно, т. к. используется одна модель для двух форм на одной странице. Посмотрите на id полей, они в обеих формах генерируются одинаковые, что не верно исходя из самого понятия id элемента.

**Comment by diozdeath19** [comment]
Собственно задать id для инпута я могу только через widgetOptions, но ты сам сказал выше не использовать его, т.е выход в этой ситуации использовать разные модели ,и получается что иметь несколько форм с одной моделью на странице нельзя?

**Comment by himiklab** [comment]
Проблема в том, что id всех полей будет одинаковый, это легко можно увидеть в исходном коду получившейся страницы. По логике yii нельзя, но это работает, потому можно попробовать сделать костыль https://github.com/himiklab/yii2-recaptcha-widget/commit/7f40838d590dfcaec4688938ddbe183cd37cea51

**Comment by diozdeath19** [comment]
Проблема решилась, спасибо за оперативность!)

**Comment by eugenekurilov** [comment]
Сейчас посмотрел на код run  - там уже значительно все поменялась, проблема актуальна, что можно сделать сейчас?
