### ISSUE TITLE
g-recaptcha-respone not in my variable in model

### ISSUE THREAD

**Issue by pohuj** [himiklab/yii2-recaptcha-widget#62]
![image](https://user-images.githubusercontent.com/25555860/35962438-6f57ad00-0cc2-11e8-9f63-f38d6f4e7744.png)

![image](https://user-images.githubusercontent.com/25555860/35962476-a52d0254-0cc2-11e8-86ac-577e10c9a6f9.png)

### And after submit form, google response not in reCaptcha and form errors with message:"The verification code is incorrect." cuz Leads[reCaptcha] = ''
![image](https://user-images.githubusercontent.com/25555860/35962516-c8fa5254-0cc2-11e8-99c0-807c7988d7e8.png)

### Code doing fine until end of january when i updated my composer.json, i guess until 1.1.1 release

**Comment by himiklab** [comment]
I see no reason why this should not work. Can you show all view code?
