### ISSUE TITLE
Unknown Property error

### ISSUE THREAD

**Issue by jlapitan** [himiklab/yii2-recaptcha-widget#64]
got error message when using the widget.

Getting unknown property: himiklab\yii2\recaptcha\ReCaptcha::field

[screenshot](https://prnt.sc/ikdne6)

**Comment by himiklab** [comment]
Show view code, please.

**Comment by jlapitan** [comment]
screenshot of the form part http://prntscr.com/ikr01v

**Comment by himiklab** [comment]
Sorry, no ideas.

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/647ffbfcf1bb0045a1d58851374654af9e109c0f

**Comment by dzandrey** [comment]
The ReCaptcha Class does not have the "field" property
I rolled back to the commit version -  a483e1edfbc177cad300bf2fa390e4e0fbbd676e

**Comment by DuskoV** [comment]
I have the same problem with later 1.2.0 version. Any news?

**Comment by himiklab** [comment]
Use yii2 >= 2.0.11.
