### ISSUE TITLE
recaptcha not rendered

### ISSUE THREAD

**Issue by marcinbarcinski** [himiklab/yii2-recaptcha-widget#66]
Hi, 

I'm trying to run widget.

I pasted this code in the view requested via ajax:

`<?= \himiklab\yii2\recaptcha\ReCaptcha::widget(['name' => 'reCaptcha']) ?>`

And after pageloads I see this in source code. No js etc.

`<div id="w0-reCaptcha-recaptcha" class="g-recaptcha" data-sitekey="xxx" input-id="w0-reCaptcha" form-id=""></div>`

How to run it properly?

**Comment by himiklab** [comment]
Hello!
Use `renderAjax()` in controller.
