### ISSUE TITLE
Перестал работать после обновления

### ISSUE THREAD

**Issue by jeebus3000** [himiklab/yii2-recaptcha-widget#67]
Привет!
После обновления на свежайшую версию виджета, он перестал пропускать отправку формы, даже если гугол разрешил.
Tag 1.1.1 работает как обычно, а в 1.1.2 такая проблема. 

Форма с опциями: `"enableAjaxValidation" => FALSE, "enableClientValidation" => TRUE`

**Comment by himiklab** [comment]
Привет!
Можете запустить отладку и определить где проблема? Может есть ошибки в логах php или js?
И/или код формы.

**Comment by jeebus3000** [comment]
Проблема возникает из-за переопределения id: `ActiveForm::begin(["options" => ["id" => "message-text"]])`.
Мне понадобился якорь на форму, для того и задал свой id.

**Comment by himiklab** [comment]
А чем плох вариант
`ActiveForm::begin(["id" => "message-text"])`?

**Comment by himiklab** [comment]
Хотя Ваш вариант тоже будет теперь работать
https://github.com/himiklab/yii2-recaptcha-widget/commit/35c9a4ae38ad20e0b4db8e9030c3744f2572dda7

**Comment by jeebus3000** [comment]
Спасибо!
