### ISSUE TITLE
Тесты для формы с yii2-recaptcha-widget

### ISSUE THREAD

**Issue by apekoff** [himiklab/yii2-recaptcha-widget#68]
Привет, посдкажите как правильно написать тест для формы с recaptcha ?
Как пройти валидацию ?
Можно ли для тестов отключить рекапчу и как ? 
```
public function checkYii2Password(FunctionalTester $I)
    {
        $I->wantTo('Проверить верный Yii2 пароль');
        $I->see('Вход', self::LOGIN_BUTTON);
        $user = $I->grabFixture('user', 'userYii2Pass');
        $I->submitForm(self::FORM_ID, $this->formParams($user['email'], '12345678'));
        $I->dontSee('Вход', self::LOGIN_BUTTON);
        $I->amLoggedInAs($user['id']);
    }

**Comment by rugabarbo** [comment]
Используйте для тестов эти ключи:

```php
'components' => [
    'reCaptcha' => [
        'siteKey' => '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI',
        'secret' => '6LeIxAcTAAAAAGG-vFI1TnRWxMZNFuojJ4WifJWe',
    ],
```

Это специальные тестовые параметры, с которыми валидация проходит всегда без проверки: https://developers.google.com/recaptcha/docs/faq

**Comment by apekoff** [comment]
Да, спасибо - это помогло. Прописал в компоненты для всех приложений.  + В самом тесте передаю в параметре `'LoginForm[reCaptcha]' => 'testme'
