### ISSUE TITLE
Cannot use with ActiveForm::begin(['enableAjaxValidation' => true])

### ISSUE THREAD

**Issue by codyng** [himiklab/yii2-recaptcha-widget#75]
Hi author,

Your lib is great but I found that it cannot be used with the form that is set using Ajax globally.

$form = ActiveForm::begin([
    'id' => 'register-form',
    'enableAjaxValidation' => true
]);

I've spent much time to find the problem already.... ><
Will you add the support to it, in case others set the form using ajax globally...

thx so much

**Comment by onmotion** [comment]
Also faced with this. It's not the widget issue. You just need to disable ajax validation for field:
`echo $form->field($user, 'reCaptcha', ['enableAjaxValidation' => false])->widget(\himiklab\yii2\recaptcha\ReCaptcha::class);`

Suggest add this case to the docs.

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/48cbc958bea004cf41f3774a4a1d445f42499fbc

**Comment by atomrus1993** [comment]
> Also faced with this. It's not the widget issue. You just need to disable ajax validation for field:
> `echo $form->field($user, 'reCaptcha', ['enableAjaxValidation' => false])->widget(\himiklab\yii2\recaptcha\ReCaptcha::class);`
> 
> Suggest add this case to the docs.

please @himiklab  add to readme this!)
