### ISSUE TITLE
What is `input-id` and `form-id` attributes?

### ISSUE THREAD

**Issue by w3lifer** [himiklab/yii2-recaptcha-widget#77]
From https://validator.w3.org

![1](https://user-images.githubusercontent.com/14075412/41733738-83a26ff0-758d-11e8-8a3c-9f568fedc2b7.png)

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/cc8a023bf51db3b40f1b8532cd94fc00c532edf5
