### ISSUE TITLE
onsubmit

### ISSUE THREAD

**Issue by ptcrank** [himiklab/yii2-recaptcha-widget#78]
Hello
Please provide an example with the following settings: 
  onsubmit and invisible

When clicked on submit, it will be displayed
Thank you very much

**Comment by himiklab** [comment]
Hello!
What should be displayed?

**Comment by mano1617** [comment]
I integrated the recaptcha in my localhost setup and i can able to see the captcha and validation , once after clicking the checkbox and green tick comes submit action not working , do we need to include  any checks in the login controller ? please let me know

**Comment by himiklab** [comment]
Use `ReCaptchaValidator` in model\`s `rules` and check `validate()` in controller.

**Comment by nomadtechiemike** [comment]
I have added the code and the recaptcha is displayed, however I can still login without cicking on the recaptcha - where is the validation check? 

` public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::class,
                'rules' => [
                    ['allow' => true, 'actions' => ['login', 'auth'], 'roles' => ['?']],
                    ['allow' => true, 'actions' => ['login', 'auth', 'logout'], 'roles' => ['@']],
					
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::class,
                'actions' => [
                    'logout' => ['post'],
                ],
            ],
        ];
    }

    /**
     * @return array
     */
    public function actions()
    {
        return [
            'auth' => [
                'class' => AuthAction::class,
                'successCallback' => Yii::$app->user->isGuest
                    ? [$this, 'authenticate']
                    : [$this, 'connect'],
            ],
        ];
    }

    /**
     * @return string|Response
     * @throws \yii\base\ExitException
     * @throws \yii\base\InvalidConfigException
     */
    public function actionLogin()
    {
        if (!\Yii::$app->user->isGuest) {
            $this->goHome();
        }

        /** @var LoginForm $model */
        $model = \Yii::createObject(LoginForm::class);
        $event = $this->getFormEvent($model);

        $this->performAjaxValidation($model);

        $this->trigger(self::EVENT_BEFORE_LOGIN, $event);

        if ($model->load(\Yii::$app->getRequest()->post()) && $model->login()) {
            $this->trigger(self::EVENT_AFTER_LOGIN, $event);
            return $this->goBack();
        }

        return $this->render('login', [
            'model' => $model,
        ]);
    }

    /**
     * @return Response
     * @throws \yii\base\InvalidConfigException
     */
    public function actionLogout()
    {
        $event = $this->getUserEvent(Yii::$app->user->identity);
        $this->trigger(self::EVENT_BEFORE_LOGOUT, $event);
        Yii::$app->getUser()->logout();
        $this->trigger(self::EVENT_AFTER_LOGOUT, $event);

        return $this->goHome();
    }

    /**
     * @param ClientInterface $client
     * @throws \yii\base\Exception
     * @throws \yii\base\InvalidConfigException
     */
    public function authenticate(ClientInterface $client)
    {
        $account = $this->finder->findAccount()->byClient($client)->one();

        if ($account === null) {
            /** @var Account $account */
            $accountObj = \Yii::createObject(Account::class);
            $account = $accountObj::create($client);
        }

        $event = $this->getAuthEvent($account, $client);
        $this->trigger(self::EVENT_BEFORE_AUTHENTICATE, $event);

        if ($account->user instanceof User) {
            if ($account->user->isBlocked) {
                Yii::$app->session->setFlash('danger', Yii::t('app', 'Your account has been blocked.'));
                $this->action->successUrl = Url::to(['/security/login']);
            } else {
                $account->user->updateAttributes(['last_login_at' => time()]);
                Yii::$app->user->login($account->user, (new LoginForm($this->finder))->rememberFor);
                $this->action->successUrl = \Yii::$app->getUser()->getReturnUrl();
            }
        } else {
            $this->action->successUrl = $account->getConnectUrl();
        }

        $this->trigger(self::EVENT_AFTER_AUTHENTICATE, $event);
    }

    /**
     * @param ClientInterface $client
     * @throws \yii\base\InvalidConfigException
     */
    public function connect(ClientInterface $client)
    {
        /** @var Account $account */
        $account = \Yii::createObject(Account::class);
        $event = $this->getAuthEvent($account, $client);

        $this->trigger(self::EVENT_BEFORE_CONNECT, $event);

        $account->connectWithUser($client);

        $this->trigger(self::EVENT_AFTER_CONNECT, $event);

        $this->action->successUrl = Url::to(['/settings/networks']);
    }
}`

this is my security controler code
