### ISSUE TITLE
multiple widgets in same page support

### ISSUE THREAD

**Issue by antokara** [himiklab/yii2-recaptcha-widget#8]
Not sure if I am missing something, but according to the google reCaptcha documentation it is possible (and I have tested it) to have multiple reCaptcha Widgets at the same page for different forms with the same keys as well.

Problem is, I could not find a way to implement it with the yii2-recaptcha-widget.
I tried using different field names as well but to no avail. I think the proper javascript code is missing in such scenarios...

**Comment by joeyblack835** [comment]
Guys, could you tell whether it is implemented or not.
Thanks.

**Comment by nikoliveira** [comment]
já é possível inserir vários recaptchas na mesma página?

**Comment by jeesus** [comment]
Updates?

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/234029e5a1e8a07f96f69ed7ed1fcb46769bbb37
