### ISSUE TITLE
Can not be used in way like this

### ISSUE THREAD

**Issue by Apache02** [himiklab/yii2-recaptcha-widget#81]
```php
<?= \himiklab\yii2\recaptcha\ReCaptcha::widget([
	'name' => 'SurveyForm[reCaptcha]',
]) ?>
```
Generated id for hidden input looks ``` w4-SurveyForm[reCaptcha] ```, and selector looks ``` #w4-SurveyForm[reCaptcha] ```.
And there is no solution to set normal id for hidden input field.

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/cc46bd4f9e6f5b86af7ebc731d6f8d1b0c06ee13
