### ISSUE TITLE
Class 'yii\httpclient\Client' not found in ReCaptchaValidator.php 

### ISSUE THREAD

**Issue by supreetSekhon** [himiklab/yii2-recaptcha-widget#84]
I have added the dependency httpclient still getting error in RecaptchaValidtor.php at line 57
  $this->httpClientRequest = (new HttpClient())->createRequest();

Kindly help. No information is provided on google related to this content.

**Comment by wingsryder** [comment]
I have got same issue... any fix?

**Comment by himiklab** [comment]
I can not reproduce the error.

**Comment by timcox99** [comment]
I get the same error. Go to this page and click on the Contact Us at the bottom of the page: https://developer.connecttel.com/sraccess/web/.  I get this error: Error
Class 'himiklab\yii2\recaptcha\HttpClient' not found

**Comment by ashfaqahmed** [comment]
Class 'yii\httpclient\Client' not found error 
PHP 7.3 
Yii2

**Comment by supreetSekhon** [comment]
Which version are you using @ashfaqahmed as I encountered this problem 2 years ago don't really remember it.
One quick question - Did you install the plugin via composer or downloaded it?

Thanks!!

**Comment by ashfaqahmed** [comment]
Hi @supreetSekhon i had it downloaded manually, so i had to re-install yii\httpclient after installing that it worked well so all good .

Thank you

**Comment by supreetSekhon** [comment]
Nice to hear that!!

My suggestion is to install all the plugins via composer as some plugins have dependencies which get downloaded automatically via composer.

Have a great day!!
