### ISSUE TITLE
Getting unknown property: yii\web\Application::reCaptcha

### ISSUE THREAD

**Issue by amirkhh** [himiklab/yii2-recaptcha-widget#85]
Hi, I've used your useful widget but I get this error:
Getting unknown property: yii\web\Application::reCaptcha

I used this widget in another project and every things was fine. 

```php
Model:
public $reCaptcha;

public function rules()
    {
        return [
           [['reCaptcha'], ReCaptchaValidator::className(), 'secret' => Yii::$app->params['reCAPTCHA.secretKey']],
        ];
    }
------------------------------------------------------------
View:
<?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className(), ['secret' => Yii::$app->params['reCAPTCHA.secretKey']]) ?>

```

thank you.

**Comment by IllegalNick** [comment]
Don't forget add recaptcha as component in your config file:

> 
> 'components' => [
>     'reCaptcha' => [
>         'name' => 'reCaptcha',
>         'class' => 'himiklab\yii2\recaptcha\ReCaptcha',
>         'siteKey' => 'your siteKey',
>         'secret' => 'your secret key',
>  ],
