### ISSUE TITLE
V3 Recaptcha not working

### ISSUE THREAD

**Issue by agsachdev** [himiklab/yii2-recaptcha-widget#87]
Please add google Recaptcha v3

**Comment by agsachdev** [comment]
How many days ?

**Comment by agsachdev** [comment]
Solved Or Not @himiklab ?

**Comment by agsachdev** [comment]
@himiklab ???

**Comment by agsachdev** [comment]
how much time more? @himiklab

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/be37ddccb2f67962944213504933725083bd6314
