### ISSUE TITLE
Change key in registerJsFile

### ISSUE THREAD

**Issue by wirgen** [himiklab/yii2-recaptcha-widget#88]
Most often in registerJsFile third argument (key) is path to js file. In this extension argument is overrided and, for example, https://github.com/skeeks-semenov/yii2-assets-auto-compress can't worked properly. Can you remove argument in registerJsFile?

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/30045aa93e6dd398ff4d0b919c0796984569b54d
