### ISSUE TITLE
eCAPTCHA has already been rendered in this element & require validation not working

### ISSUE THREAD

**Issue by bschauhan** [himiklab/yii2-recaptcha-widget#89]
**In Config:**
```
'reCaptcha' => [
            'name' => 'reCaptcha',
            'class' => 'himiklab\yii2\recaptcha\ReCaptcha',
            'siteKey' => '6LfytA4TAAAAACPWwCQYi2eX8pO9evDt9pSoSus0', 
            'secret' => '6LfytA4TAAAAAAUL7wANH2ti75sois_wOrZezEhE',
        ],
```

**In Model:**
`[['reCaptcha'],\himiklab\yii2\recaptcha\ReCaptchaValidator::className(), 'secret' => 'xxxxxxxxxx''],`

**In Form:**
`<?= $form->field($model, 'reCaptcha')->widget(\himiklab\yii2\recaptcha\ReCaptcha::className())->label(false) ?>`

**Javascript Error:**

recaptcha__en.js:501 Uncaught Error: reCAPTCHA has already been rendered in this element
    at Object.RP [as render] (VM2700 recaptcha__en.js:501)
    at HTMLDivElement.<anonymous> (escort_agency_register:603)
    at Function.each (jquery.js:362)
    at jQuery.fn.init.each (jquery.js:157)
    at recaptchaOnloadCallback (escort_agency_register:600)
    at gf (VM2700 recaptcha__en.js:498)
    at Gj (VM2700 recaptcha__en.js:494)
    at VM2700 recaptcha__en.js:506
    at VM2700 recaptcha__en.js:525

**Comment by carlositos** [comment]
Fix is here - https://github.com/sashsvamir/yii2-recaptcha-widget/commit/1719b0af15fa04aed6dbf79d07fe3b0b51632549
