### ISSUE TITLE
composer doesn't install Recaptcha3

### ISSUE THREAD

**Issue by Slip31** [himiklab/yii2-recaptcha-widget#95]
After php composer.phar require --prefer-dist "himiklab/yii2-recaptcha-widget" "*" composer installed only 
 `ReCaptcha` and
`ReCaptchaValidator` in vendor\himiklab\yii2-recaptcha-widget

No ReCaptcha2 and others

**Comment by himiklab** [comment]
Until the stable version comes out, install the @dev version.

**Comment by numelion** [comment]
There is no dev branch, only master

**Comment by himiklab** [comment]
"himiklab/yii2-recaptcha-widget": "@dev"
