### ISSUE TITLE
Getting unknown property: himiklab\yii2\recaptcha\ReCaptcha::httpClientRequest

### ISSUE THREAD

**Issue by fabiotomasatti** [himiklab/yii2-recaptcha-widget#97]
In the new version 2.1.0 there's this error:
Getting unknown property: himiklab\yii2\recaptcha\ReCaptcha::httpClientRequest

In the previous version 2.0.0 the error does not exist.

**Comment by Thoulah** [comment]
Same issue for me. Downgraded to 2.0.0 to have a working setup.

**Comment by himiklab** [comment]
https://github.com/himiklab/yii2-recaptcha-widget/commit/341ae7e19e12783f3dfd8984a49185e0a44021ea
