### ISSUE TITLE
Can't find variable: grecaptcha when using renderAjax()

### ISSUE THREAD

**Issue by stevekr** [himiklab/yii2-recaptcha-widget#99]
When using `renderAjax()` I get `Can't find variable: grecaptcha` error.

Version 2.1.1

**Comment by phrakon** [comment]
As a temporary solution

override Recaptcha3 class and change

`        $url = $this->jsApiUrl . '?' . $arguments;
        $view->registerJs(
            <<<JS
"use strict";
$.getScript('$url').done(function() {
    grecaptcha.ready(function() {
        grecaptcha.execute("{$this->siteKey}", {action: "{$this->action}"}).then(function(token) {
            jQuery("#" + "{$this->getReCaptchaId()}").val(token);
    
            const jsCallback = "{$this->jsCallback}";
            if (jsCallback) {
                eval("(" + jsCallback + ")(token)");
            }
        });
    });    
});
JS
            , $view::POS_READY);`
